export const DRUGS = 'гидра, hydra, меф, трава, травка, джойнт, гашиш, марихуана, бошки, шишки, бонг, вапорайзер, кокаин, ксанакс'
export const POLITICS = 'путин, тоталитаризм, революция, митинг, болотная'
export const UKRAINE = 'зеленский, украина, майдан'
export const PRIVATE_LIFE = 'секс, мастурбация, нюдс'
export const BLOCKED_SITES = 'meduza.io, novayagazeta.ru'
